include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    dead_code: info
    unused_import: warning
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**

linter:
  rules:
    - avoid_dynamic_calls
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_locals
    - unnecessary_lambdas
    - use_super_parameters
    - avoid_print
    - prefer_single_quotes